# Generated by Django 3.2.7 on 2021-10-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Category',
            new_name='OfferCategory',
        ),
    ]
